### ISSUE TITLE
Issue bug hot fix

### ISSUE THREAD

**Issue by DevilIris** [Wolferos/Hearts-of-Iron-IV-The-Great-War#139] opened 2017-08-21 16:53 UTC
So apparently a lot of people cant save their games and continue in the game. Any ideas about the bug?  

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DevilIris** [comment] 2017-08-21 17:13
Also belgium have localisations errors in their fpcus tree. As well the impassable areas that we need to fix

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MasterWaifuman** [comment] 2017-08-21 17:19
Belgium loc errors because Wolferos added BEL_ in political branch ids

**Comment by DevilIris** [comment] 2017-08-21 17:30
Also in the Soviet union Fpcus tree when they pick peoples army the game crash.

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MasterWaifuman** [comment] 2017-08-21 17:32
it is not focus. this is event to load oob it fires after revolution

**Comment by MasterWaifuman** [comment] 2017-08-21 17:33
I think it crashes for same reason why it don't load from revolution event

**Comment by MasterWaifuman** [comment] 2017-08-21 17:33
but the reason itself unknown

**Comment by MasterWaifuman** [comment] 2017-08-21 17:33
like reason for crashes on continuing game

**Comment by MasterWaifuman** [comment] 2017-08-21 17:34
i'm trying to find solution right now

**Comment by MasterWaifuman** [comment] 2017-08-21 17:37
threre is string in the log that says "[20:23:06][effectimplementation.cpp:6717]: Unkown focus scripted mex_ww1_industrial_effort"

**Comment by DevilIris** [comment] 2017-08-21 17:38
Also this is for the new update of VP 

While I like the new Bulgarian VPs there are some glaring flaws:
- Montana should be named Ferdinand (the name Montana wont be given until the 1990s)
- Weliko is not the name of the city its Veliko Turnovo (the term Weliko is used to signify old capitals)
- Major cities like Ruse and Stara Zagora are absent, while much smaller cities are present.
----------------'xx

As well in next update we can have the unit baltic ducby their own focus tree as well

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DevilIris** [comment] 2017-08-21 17:39
That is the mexican focus tree . What happen with it?

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MasterWaifuman** [comment] 2017-08-21 17:44
dunno. trying to find out.

**Comment by MasterWaifuman** [comment] 2017-08-21 17:45
it says that something with effect

**Comment by DevilIris** [comment] 2017-08-21 17:50
I check it and it works well for me .


Alsl i need to check again the Xinhai Revolution.

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MasterWaifuman** [comment] 2017-08-21 17:53
i think this isn't some obvious errors. It is like load oob problem with abdication of nicholas. It might look and work well but in fact cause errors.

**Comment by MasterWaifuman** [comment] 2017-08-21 18:05
i committed experiment. i changed id of focus, but the log still says "Unkown focus scripted mex_ww1_industrial_effort"

**Comment by MasterWaifuman** [comment] 2017-08-21 18:06
maybe you mentioned this focus somewhere, in event maybe or somewhere else

**Comment by MasterWaifuman** [comment] 2017-08-21 18:09
I found out

**Comment by MasterWaifuman** [comment] 2017-08-21 18:12
`1910.1.1 = {
	oob = "MEX_1910"

	#-------------------------------------------------------
	#							NF
	#-------------------------------------------------------
	#Army
	complete_national_focus = mex_political_effort
	complete_national_focus = mex_ww1_industrial_effort

	#Diplomatic
	complete_national_focus = mex_ww1_diplomatic_effort
	#-------------------------------------------------------`

in code capital letters are important. for example in console you can type tag like "fra" or "ger" but in code they must be exact "FRA" and "GER". But if you mention ids somewhere they must be exact as they were set.

**Comment by MasterWaifuman** [comment] 2017-08-21 18:13
so it must be `1910.1.1 = {
	oob = "MEX_1910"

	#-------------------------------------------------------
	#							NF
	#-------------------------------------------------------
	#Army
	complete_national_focus = mex_political_effort
	complete_national_focus = MEX_ww1_industrial_effort

	#Diplomatic
	complete_national_focus = mex_ww1_diplomatic_effort
	#-------------------------------------------------------`

**Comment by DevilIris** [comment] 2017-08-21 18:35
Oh ok. We need that push in the develop
 Any other bug?

DevilIris

**Comment by MasterWaifuman** [comment] 2017-08-21 18:36
i'm working on soviet oob load bug

**Comment by MasterWaifuman** [comment] 2017-08-21 19:12
what the? you remember that when event nicholas abdicates was firing game didn't load oob for sov. to fix this i created event that load sov oob. now to fix crash caused by this event i returned comand load oob into nicholas abdicates event and now it works. that game code is weird.

**Comment by DevilIris** [comment] 2017-08-21 19:16
Lol, well in that case you could rewrite the obbs that you made. So you can
merge it with the original

DevilIris

**Comment by MasterWaifuman** [comment] 2017-08-21 19:18
i didn't make oobs. i just moved command "load_oob = SOV_Revolt_01" from one event to another.

**Comment by MasterWaifuman** [comment] 2017-08-21 19:20
also i don't know how to fix crash when load saved game. log also quiet

**Comment by DevilIris** [comment] 2017-08-21 19:21
same for me the log has the normal things. Either idk what is crahsing or destroying the game saves

**Comment by MasterWaifuman** [comment] 2017-08-21 19:57
maybe Wolferos has some ideas. i just give up

**Comment by MasterWaifuman** [comment] 2017-08-21 20:00
hmmm... i think you gave me idea. i'll try to check save files (it is 588171 strings so it would veeery difficult). But tell me if you want to help. i can give my crash test save file.

**Comment by DevilIris** [comment] 2017-08-21 20:02
I already have a save file until 1918 

the problem here is what is making killing the Game saves. other main thing can be the defines but i dont see anything wrong.  But this is a serious problem in the mod

**Comment by DevilIris** [comment] 2017-08-21 20:03
Also i am going to give up i dont see anything wrong. Idk what is making killing the Game saves.

**Comment by DevilIris** [comment] 2017-08-21 20:04
The log dont tell me anything that cause the that eror

**Comment by MasterWaifuman** [comment] 2017-08-21 20:16
I will try some radical measures. i will temporarily deleting things that i know we changed and try to find out that caused broken saves

**Comment by MasterWaifuman** [comment] 2017-08-21 20:37
i think i will do that later (when pirate update comes out). So i leave it to you.

**Comment by MasterWaifuman** [comment] 2017-08-21 23:13
i downloaded 0.3.2 and imported here all my things (NFs, events, gfx) and saves load. that means it is something from others. i will now slowly and metodically import ither things. and will hope i find fix for crashes

**Comment by DevilIris** [comment] 2017-08-21 23:15
ok you can do it as always in my rep . i will test for you. In the new Version so we can do it a pull request

**Comment by DevilIris** [comment] 2017-08-22 08:52
I fix the areas of africa but i ididnt find the belgium files of localisation

_Sent from my Samsung SM-G532M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MasterWaifuman** [comment] 2017-08-22 08:54
i keep all localisation in one file ( not to update every file in repo if i need to update loc )

**Closed as completed** 2017-08-23 17:30 UTC
